"""initial_schema

Revision ID: ebc0d3f036ab
Revises: None
Create Date: 2026-08-12 17:20:30.097263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc0d3f036ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def get_inspector():
    bind = op.get_bind()
    return sa.inspect(bind)


def table_exists(table_name: str, schema: str = None) -> bool:
    inspector = get_inspector()
    return table_name in inspector.get_table_names(schema=schema)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('users'):
        op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
        )
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    if not table_exists('organizations'):
        op.create_table('organizations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('type', sa.Enum('INDIVIDUAL', 'CONSULTANCY', name='orgtype'), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_organizations_owner_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
        )
        with op.batch_alter_table('organizations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    if not table_exists('audit_logs'):
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=100), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
        )
        with op.batch_alter_table('audit_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    if not table_exists('candidates'):
        op.create_table('candidates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('current_title', sa.String(length=150), nullable=True),
        sa.Column('current_company', sa.String(length=150), nullable=True),
        sa.Column('experience_years', sa.Float(), nullable=True),
        sa.Column('notice_period_days', sa.Integer(), nullable=True),
        sa.Column('current_salary', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('expected_salary', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('primary_skills', sa.Text(), nullable=True),
        sa.Column('secondary_skills', sa.Text(), nullable=True),
        sa.Column('skills', sa.Text(), nullable=True),
        sa.Column('assigned_counselor_id', sa.Integer(), nullable=True),
        sa.Column('assigned_recruiter_id', sa.Integer(), nullable=True),
        sa.Column('source', sa.String(length=100), nullable=True),
        sa.Column('resume_url', sa.String(length=500), nullable=True),
        sa.Column('status', sa.Enum('NEW', 'SCREENING', 'READY', 'SUBMITTED', 'INTERVIEWING', 'OFFERED', 'PLACED', 'ON_HOLD', 'REJECTED', 'INACTIVE', name='candidatestatus'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['assigned_counselor_id'], ['users.id'], name=op.f('fk_candidates_assigned_counselor_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['assigned_recruiter_id'], ['users.id'], name=op.f('fk_candidates_assigned_recruiter_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_candidates_organization_id_organizations'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidates_user_id_users'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
        )
        with op.batch_alter_table('candidates', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_candidates_id'), ['id'], unique=False)
            batch_op.create_index('ix_candidates_org_email', ['organization_id', 'email'], unique=False)
            batch_op.create_index(batch_op.f('ix_candidates_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_candidates_user_id'), ['user_id'], unique=False)

    if not table_exists('companies'):
        op.create_table('companies',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_companies_organization_id_organizations'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
        )
        with op.batch_alter_table('companies', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
            batch_op.create_index('ix_companies_org_name', ['organization_id', 'name'], unique=False)
            batch_op.create_index(batch_op.f('ix_companies_organization_id'), ['organization_id'], unique=False)

    if not table_exists('followups'):
        op.create_table('followups',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('assigned_user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='followupstatus'), nullable=False),
        sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='followuppriority'), nullable=False),
        sa.Column('entity_type', sa.Enum('COMPANY', 'CONTACT', 'REQUIREMENT', 'APPLICATION', name='entitytype'), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_followups_assigned_user_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_followups_organization_id_organizations'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_followups'))
        )
        with op.batch_alter_table('followups', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_followups_assigned_user_id'), ['assigned_user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_followups_due_date'), ['due_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_followups_entity_id'), ['entity_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_followups_id'), ['id'], unique=False)
            batch_op.create_index('ix_followups_org_due_status', ['organization_id', 'due_date', 'status'], unique=False)
            batch_op.create_index(batch_op.f('ix_followups_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_followups_status'), ['status'], unique=False)

    if not table_exists('invitations'):
        op.create_table('invitations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', 'COUNSELOR', 'CANDIDATE', name='orgrole'), nullable=False),
        sa.Column('token', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus'), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_invitations_created_by_user_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invitations_organization_id_organizations'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
        )
        with op.batch_alter_table('invitations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
            batch_op.create_index(batch_op.f('ix_invitations_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_invitations_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    if not table_exists('organization_memberships'):
        op.create_table('organization_memberships',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', 'COUNSELOR', 'CANDIDATE', name='orgrole'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_memberships_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
        sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user_membership')
        )
        with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_organization_memberships_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_organization_memberships_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_organization_memberships_user_id'), ['user_id'], unique=False)

    if not table_exists('contacts'):
        op.create_table('contacts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('designation', sa.String(length=150), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('linkedin_url', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('source', sa.String(length=100), nullable=True),
        sa.Column('status', sa.Enum('NOT_CONTACTED', 'CONTACTED', 'INTERESTED', 'KEEP_IN_TOUCH', 'OPPORTUNITY_AVAILABLE', 'NOT_RELEVANT', 'DO_NOT_CONTACT', name='contactstatus'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contacts_organization_id_organizations'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
        )
        with op.batch_alter_table('contacts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
            batch_op.create_index('ix_contacts_org_company', ['organization_id', 'company_id'], unique=False)
            batch_op.create_index('ix_contacts_org_email', ['organization_id', 'email'], unique=False)
            batch_op.create_index(batch_op.f('ix_contacts_organization_id'), ['organization_id'], unique=False)

    if not table_exists('documents'):
        op.create_table('documents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_type', sa.String(length=100), nullable=False),
        sa.Column('file_url', sa.String(length=500), nullable=False),
        sa.Column('doc_type', sa.Enum('RESUME', 'CERTIFICATE', 'ID_DOCUMENT', 'OTHER', name='documenttype'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_documents_candidate_id_candidates'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
        )
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_documents_candidate_id'), ['candidate_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)

    if not table_exists('calls'):
        op.create_table('calls',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('candidate_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('call_type', sa.Enum('OUTBOUND', 'INBOUND', 'DISCOVERY', 'FOLLOWUP', name='calltype'), nullable=False),
        sa.Column('outcome', sa.Enum('CONNECTED', 'NO_ANSWER', 'BUSY', 'CALL_BACK', 'WRONG_NUMBER', 'NOT_HIRING', 'OPPORTUNITY_AVAILABLE', 'RESUME_REQUESTED', 'REQUIREMENT_CLOSED', 'NOT_RELEVANT', 'OTHER', name='calloutcome'), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=False),
        sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_calls_candidate_id_candidates'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_calls_contact_id_contacts'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_calls_organization_id_organizations'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calls_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
        )
        with op.batch_alter_table('calls', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_calls_candidate_id'), ['candidate_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_calls_contact_id'), ['contact_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_calls_id'), ['id'], unique=False)
            batch_op.create_index('ix_calls_org_contact', ['organization_id', 'contact_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_calls_organization_id'), ['organization_id'], unique=False)

    if not table_exists('job_requirements'):
        op.create_table('job_requirements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('work_mode', sa.Enum('HYBRID', 'REMOTE', 'ONSITE', name='workmode'), nullable=False),
        sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='requirementpriority'), nullable=False),
        sa.Column('experience_req', sa.String(length=100), nullable=True),
        sa.Column('min_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column('max_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column('skills_req', sa.Text(), nullable=True),
        sa.Column('employment_type', sa.Enum('FULL_TIME', 'CONTRACT', 'PART_TIME', 'INTERNSHIP', name='employmenttype'), nullable=False),
        sa.Column('source', sa.String(length=100), nullable=True),
        sa.Column('openings_count', sa.Integer(), nullable=False),
        sa.Column('min_salary', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('max_salary', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('status', sa.Enum('OPEN', 'NEW', 'INTERESTED', 'APPLIED', 'FOLLOW_UP', 'INTERVIEWING', 'OFFER', 'ON_HOLD', 'CLOSED', 'CANCELLED', 'REJECTED', name='requirementstatus'), nullable=False),
        sa.Column('open_date', sa.Date(), nullable=True),
        sa.Column('closing_date', sa.Date(), nullable=True),
        sa.Column('assigned_recruiter_id', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['assigned_recruiter_id'], ['users.id'], name=op.f('fk_job_requirements_assigned_recruiter_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_job_requirements_company_id_companies'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_job_requirements_contact_id_contacts'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_job_requirements_organization_id_organizations'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirements'))
        )
        with op.batch_alter_table('job_requirements', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_job_requirements_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_job_requirements_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_job_requirements_organization_id'), ['organization_id'], unique=False)
            batch_op.create_index('ix_requirements_org_status', ['organization_id', 'status'], unique=False)

    if not table_exists('applications'):
        op.create_table('applications',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('job_requirement_id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('stage', sa.Enum('APPLIED', 'SUBMITTED', 'SCREENING', 'INTERVIEWING', 'OFFERED', 'PLACED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_applications_candidate_id_candidates'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], name=op.f('fk_applications_job_requirement_id_job_requirements'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_applications_organization_id_organizations'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
        )
        with op.batch_alter_table('applications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_applications_candidate_id'), ['candidate_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_applications_job_requirement_id'), ['job_requirement_id'], unique=False)
            batch_op.create_index('ix_applications_org_req_cand', ['organization_id', 'job_requirement_id', 'candidate_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_applications_organization_id'), ['organization_id'], unique=False)

    if not table_exists('submissions'):
        op.create_table('submissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('job_requirement_id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('SUBMITTED', 'SHORTLISTED', 'CLIENT_REVIEW', 'INTERVIEW', 'OFFER', 'PLACED', 'REJECTED', 'WITHDRAWN', name='submissionstatus'), nullable=False),
        sa.Column('client_feedback', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_submissions_candidate_id_candidates'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], name=op.f('fk_submissions_job_requirement_id_job_requirements'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_submissions_organization_id_organizations'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_submissions_submitted_by_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
        )
        with op.batch_alter_table('submissions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_submissions_candidate_id'), ['candidate_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_submissions_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_submissions_job_requirement_id'), ['job_requirement_id'], unique=False)
            batch_op.create_index('ix_submissions_org_req_cand', ['organization_id', 'job_requirement_id', 'candidate_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_submissions_organization_id'), ['organization_id'], unique=False)

    if not table_exists('interviews'):
        op.create_table('interviews',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=False),
        sa.Column('round_name', sa.String(length=150), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('location_or_link', sa.String(length=500), nullable=True),
        sa.Column('interviewer_names', sa.String(length=255), nullable=True),
        sa.Column('outcome', sa.Enum('SCHEDULED', 'COMPLETED', 'PASSED', 'FAILED', 'RESCHEDULED', 'CANCELLED', name='interviewoutcome'), nullable=False),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_interviews_application_id_applications'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
        )
        with op.batch_alter_table('interviews', schema=None) as batch_op:
            batch_op.create_index('ix_interviews_app_scheduled', ['application_id', 'scheduled_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_interviews_application_id'), ['application_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_interviews_id'), ['id'], unique=False)

    if not table_exists('offers'):
        op.create_table('offers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=False),
        sa.Column('offered_salary', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('joining_date', sa.Date(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'REVISED', name='offerstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_offers_application_id_applications'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
        )
        with op.batch_alter_table('offers', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_offers_application_id'), ['application_id'], unique=True)
            batch_op.create_index(batch_op.f('ix_offers_id'), ['id'], unique=False)

    if not table_exists('placements'):
        op.create_table('placements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=True),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('job_requirement_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('join_date', sa.Date(), nullable=False),
        sa.Column('offered_salary', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('billing_amount', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('recruiter_id', sa.Integer(), nullable=True),
        sa.Column('counselor_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('EXPECTED', 'CONFIRMED', 'JOINED', 'DID_NOT_JOIN', 'ACTIVE', 'COMPLETED', 'EARLY_EXIT', 'CANCELLED', name='placementstatus'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_placements_application_id_applications'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_placements_candidate_id_candidates'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_placements_company_id_companies'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], name=op.f('fk_placements_counselor_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], name=op.f('fk_placements_job_requirement_id_job_requirements'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_placements_organization_id_organizations'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], name=op.f('fk_placements_recruiter_id_users'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_placements'))
        )
        with op.batch_alter_table('placements', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_placements_application_id'), ['application_id'], unique=True)
            batch_op.create_index(batch_op.f('ix_placements_candidate_id'), ['candidate_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_placements_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_placements_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_placements_job_requirement_id'), ['job_requirement_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_placements_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_placements_job_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_placements_id'))
        batch_op.drop_index(batch_op.f('ix_placements_company_id'))
        batch_op.drop_index(batch_op.f('ix_placements_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_placements_application_id'))

    op.drop_table('placements')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_id'))
        batch_op.drop_index(batch_op.f('ix_offers_application_id'))

    op.drop_table('offers')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_id'))
        batch_op.drop_index(batch_op.f('ix_interviews_application_id'))
        batch_op.drop_index('ix_interviews_app_scheduled')

    op.drop_table('interviews')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_organization_id'))
        batch_op.drop_index('ix_submissions_org_req_cand')
        batch_op.drop_index(batch_op.f('ix_submissions_job_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_candidate_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_organization_id'))
        batch_op.drop_index('ix_applications_org_req_cand')
        batch_op.drop_index(batch_op.f('ix_applications_job_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))
        batch_op.drop_index(batch_op.f('ix_applications_candidate_id'))

    op.drop_table('applications')
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_requirements_org_status')
        batch_op.drop_index(batch_op.f('ix_job_requirements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_job_requirements_id'))
        batch_op.drop_index(batch_op.f('ix_job_requirements_company_id'))

    op.drop_table('job_requirements')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_organization_id'))
        batch_op.drop_index('ix_calls_org_contact')
        batch_op.drop_index(batch_op.f('ix_calls_id'))
        batch_op.drop_index(batch_op.f('ix_calls_contact_id'))
        batch_op.drop_index(batch_op.f('ix_calls_candidate_id'))

    op.drop_table('calls')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_candidate_id'))

    op.drop_table('documents')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_organization_id'))
        batch_op.drop_index('ix_contacts_org_email')
        batch_op.drop_index('ix_contacts_org_company')
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_id'))

    op.drop_table('organization_memberships')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followups_status'))
        batch_op.drop_index(batch_op.f('ix_followups_organization_id'))
        batch_op.drop_index('ix_followups_org_due_status')
        batch_op.drop_index(batch_op.f('ix_followups_id'))
        batch_op.drop_index(batch_op.f('ix_followups_entity_id'))
        batch_op.drop_index(batch_op.f('ix_followups_due_date'))
        batch_op.drop_index(batch_op.f('ix_followups_assigned_user_id'))

    op.drop_table('followups')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_organization_id'))
        batch_op.drop_index('ix_companies_org_name')
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_user_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_organization_id'))
        batch_op.drop_index('ix_candidates_org_email')
        batch_op.drop_index(batch_op.f('ix_candidates_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
